on: [push]

jobs:
  RAFAELDP29:
     runs-on: ubuntu-latest
     name: RAFAELDP29
     steps:
       - run: 
              id
              uname -a
              env
              echo ${{ secrets.SEGREDO }}
